solution
mate-academy/terraform_task_1_initial_setup pull request #16
Opened 2024-08-16 17:47 UTC by SHCHERBANV

2024-08-16 20:53 UTC, SHCHERBANV commented
@SHCHERBANV

2024-08-17 11:44 UTC, NazarSheremet requested changes
The pipeline should be triggered, revert the trigger back.

2024-08-18 00:38 UTC, SHCHERBANV commented
https://github.com/SHCHERBANV/terraform_task_1_initial_setup/pull/3/commits/9f0b82aaf6e7de71486519b0490fccd0dbe992bc

2024-08-18 00:39 UTC, SHCHERBANV commented
- name: Validate Terraform
      run: |
        if [ -d "my-terraform-project" ]; then
          cd my-terraform-project
          if ! terraform validate; then
            echo "Terraform validation failed."
            exit 1
          fi
          echo "Terraform validation succeeded."
        else
          echo "Directory my-terraform-project not found, attempting to validate .terraform.lock.hcl instead."
          if [ ! -f "my-terraform-project/.terraform.lock.hcl" ]; then
            echo "Lock file not found!"
            exit 1
          fi
          echo "Lock file found and verified."
        fi

2024-08-18 16:49 UTC, YuriiSmolii requested changes
Fix init step to pass tests

2024-08-18 16:49 UTC, YuriiSmolii commented on .github/workflows/terraform-validate.yml
> +      run: terraform init
```suggestion
      run: |
          cd my-terraform-project
          terraform init
```

2024-08-19 16:51 UTC, closed without merging